name: FileDepsTreatment
version: 0.1.1
description: An experimental treatment for building with each file having its own imports
publish_to: none

environment:
  sdk: '>=2.13.0'

dependencies:
  crypto: ^3.0.1
  cryptography:
    git:
      url: git@github.com:grantnelson-wf/cryptography.git
      path: cryptography
  event: ^2.0.5
  validators: ^3.0.0

dev_dependencies:
  dart_dev: ^3.6.1
  build_runner: ^1.10.0
  build_web_compilers: '>=2.12.0'
